CREATE TABLE FORTUNE (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  text varchar(255) not null
);

INSERT INTO FORTUNE (text) VALUES ('Do what works.');

INSERT INTO FORTUNE (text) VALUES ('Do the right thing.');

INSERT INTO FORTUNE (text) VALUES ('Always be kind.');

INSERT INTO FORTUNE (text) VALUES ('You learn from your mistakes... You will learn a lot today.');

INSERT INTO FORTUNE (text) VALUES ('You can always find happiness at work on Friday.');

INSERT INTO FORTUNE (text) VALUES ('You will be hungry again in one hour.');

INSERT INTO FORTUNE (text) VALUES ('Today will be an awesome day!');